// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLocalNode(arg1) {
  return window['go']['main']['App']['AddLocalNode'](arg1);
}

export function AddSubscription(arg1, arg2) {
  return window['go']['main']['App']['AddSubscription'](arg1, arg2);
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CheckXrayUpdate() {
  return window['go']['main']['App']['CheckXrayUpdate']();
}

export function CheckXrayUpdateStatus() {
  return window['go']['main']['App']['CheckXrayUpdateStatus']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function DeleteLocalNode(arg1) {
  return window['go']['main']['App']['DeleteLocalNode'](arg1);
}

export function DeleteSubscription(arg1) {
  return window['go']['main']['App']['DeleteSubscription'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DownloadXrayUpdate() {
  return window['go']['main']['App']['DownloadXrayUpdate']();
}

export function FetchIPInfo() {
  return window['go']['main']['App']['FetchIPInfo']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetConnectionState() {
  return window['go']['main']['App']['GetConnectionState']();
}

export function GetIPInfo() {
  return window['go']['main']['App']['GetIPInfo']();
}

export function GetLocalNodes() {
  return window['go']['main']['App']['GetLocalNodes']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetResourceStatus() {
  return window['go']['main']['App']['GetResourceStatus']();
}

export function GetSelectedNodeID() {
  return window['go']['main']['App']['GetSelectedNodeID']();
}

export function GetSelectedSubID() {
  return window['go']['main']['App']['GetSelectedSubID']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSubscriptions() {
  return window['go']['main']['App']['GetSubscriptions']();
}

export function GetXrayVersion() {
  return window['go']['main']['App']['GetXrayVersion']();
}

export function RefreshAllSubscriptions() {
  return window['go']['main']['App']['RefreshAllSubscriptions']();
}

export function RefreshSubscription(arg1) {
  return window['go']['main']['App']['RefreshSubscription'](arg1);
}

export function SaveAndReload(arg1) {
  return window['go']['main']['App']['SaveAndReload'](arg1);
}

export function SaveLocalNodes(arg1) {
  return window['go']['main']['App']['SaveLocalNodes'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetSelectedNodeID(arg1) {
  return window['go']['main']['App']['SetSelectedNodeID'](arg1);
}

export function SetSelectedSubID(arg1) {
  return window['go']['main']['App']['SetSelectedSubID'](arg1);
}

export function URLTest() {
  return window['go']['main']['App']['URLTest']();
}

export function URLTestLocal() {
  return window['go']['main']['App']['URLTestLocal']();
}

export function URLTestNodes(arg1) {
  return window['go']['main']['App']['URLTestNodes'](arg1);
}

export function UpdateLocalNode(arg1) {
  return window['go']['main']['App']['UpdateLocalNode'](arg1);
}

export function UpdateSubscription(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSubscription'](arg1, arg2, arg3);
}

export function VerifyReady() {
  return window['go']['main']['App']['VerifyReady']();
}
