// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function AddLocalNode(arg1:models.Node):Promise<main.APIResponse>;

export function AddSubscription(arg1:string,arg2:string):Promise<main.APIResponse>;

export function CancelDownload():Promise<main.APIResponse>;

export function CheckXrayUpdate():Promise<main.APIResponse>;

export function CheckXrayUpdateStatus():Promise<main.APIResponse>;

export function ClearLogs():Promise<main.APIResponse>;

export function Connect():Promise<main.APIResponse>;

export function DeleteLocalNode(arg1:string):Promise<main.APIResponse>;

export function DeleteSubscription(arg1:string):Promise<main.APIResponse>;

export function Disconnect():Promise<main.APIResponse>;

export function DownloadXrayUpdate():Promise<main.APIResponse>;

export function FetchIPInfo():Promise<main.APIResponse>;

export function GetAppInfo():Promise<main.APIResponse>;

export function GetConnectionState():Promise<main.APIResponse>;

export function GetIPInfo():Promise<main.APIResponse>;

export function GetLocalNodes():Promise<main.APIResponse>;

export function GetLogs():Promise<main.APIResponse>;

export function GetResourceStatus():Promise<main.APIResponse>;

export function GetSelectedNodeID():Promise<main.APIResponse>;

export function GetSelectedSubID():Promise<main.APIResponse>;

export function GetSettings():Promise<main.APIResponse>;

export function GetSubscriptions():Promise<main.APIResponse>;

export function GetXrayVersion():Promise<main.APIResponse>;

export function RefreshAllSubscriptions():Promise<main.APIResponse>;

export function RefreshSubscription(arg1:string):Promise<main.APIResponse>;

export function SaveAndReload(arg1:models.AppSettings):Promise<main.APIResponse>;

export function SaveLocalNodes(arg1:Array<models.Node>):Promise<main.APIResponse>;

export function SaveSettings(arg1:models.AppSettings):Promise<main.APIResponse>;

export function SetSelectedNodeID(arg1:string):Promise<main.APIResponse>;

export function SetSelectedSubID(arg1:string):Promise<main.APIResponse>;

export function URLTest():Promise<main.APIResponse>;

export function URLTestLocal():Promise<main.APIResponse>;

export function URLTestNodes(arg1:Array<models.Node>):Promise<main.APIResponse>;

export function UpdateLocalNode(arg1:models.Node):Promise<main.APIResponse>;

export function UpdateSubscription(arg1:string,arg2:string,arg3:string):Promise<main.APIResponse>;

export function VerifyReady():Promise<main.APIResponse>;
